export const cheeseData = [
  {
    src: "/products/quesos/cremoso-punta-del-agua.png",
    alt: "Queso cremoso",
    title: "Queso cremoso",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.330",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/porsalut-punta-del-agua.png",
    alt: "Por salut",
    title: "Por salut",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.440",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/porsalut-light-punta-del-agua.png",
    alt: "Por salut Light",
    title: "Por salut Light",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.610",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/tybo-punta-del-agua.png",
    alt: "Tybo",
    title: "Tybo",
    description: "3,3 Kg Aprox",
    price: "$1.890",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/danbo-punta-del-agua.png",
    alt: "Danbo",
    title: "Danbo",
    description: "4,5 a 5 Kg Aprox",
    price: "$1.890",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/mozzarella-punta-del-agua.png",
    alt: "Muzzarella",
    title: "Muzzarella",
    description: "2,5 a 2,7 Kg Aprox",
    price: "$1.640",
    width: "100",
    height: "100",
  },

  {
    src: "/products/quesos/queso-sardo.png",
    alt: "Sardo",
    title: "Sardo",
    description: "3 a 3,5 Kg Aprox",
    price: "$2.590",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/fynbo-horma.png",
    alt: "Fynbo",
    title: "Fynbo",
    description: "5,5 Kg Aprox",
    price: "$1.890",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/reggianito-horma.png",
    alt: "Reggianito",
    title: "Reggianito",
    description: "6,5 a 7 Kg Aprox",
    price: "$2.590",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/sardo.png",
    alt: "Sardo fresco",
    title: "Sardo fresco",
    description: "3 a 3,5 Kg Aprox",
    price: "$1.740",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/roquefort-emperador.png",
    alt: "Roquefort",
    title: "Roquefort",
    description: "2 Kg Aprox",
    price: "$1.950",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/cremigal-por-salut-sin-sal.png",
    alt: "Por salut sin sal",
    title: "Por salut sin sal",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.640",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/cremigal-cremoso.png",
    alt: "Queso cremoso",
    title: "Queso cremoso",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.420",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/cremigal-por-salut.png",
    alt: "Por salut",
    title: "Por salut",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.590",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/cremigal-por-salut-light.png",
    alt: "Por salut Light",
    title: "Por salut Light",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.720",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/cremoso-los-alisos.png",
    alt: "Queso cremoso",
    title: "Queso cremoso",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.290",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/tybo-los-alisos.png",
    alt: "Tybo",
    title: "Tybo",
    description: "3,9 a 4,5 Kg Aprox",
    price: "$1.800",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/muzzarella-los-alisos.png",
    alt: "Muzarella",
    title: "Muzarella",
    description: "3,5 Kg Aprox",
    price: "$1.490",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/cheddar-10.png",
    alt: "Queso cheddar",
    title: "Queso cheddar",
    description: "10 fetas",
    price: "$390",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/cheddar-160.png",
    alt: "Queso cheddar",
    title: "Queso cheddar",
    description: "160 fetas",
    price: "$5.660",
    width: "100",
    height: "100",
  },
  {
    src: "/products/quesos/cheddar-sachet.png",
    alt: "Pouch Queso cheddar",
    title: "Pouch Queso cheddar",
    description: "3 Kg",
    price: "$4.800",
    width: "100",
    height: "100",
  },
];

export const cheeseBrands = [
  {
    src: "/brands/punta-del-agua.png",
    alt: "Punta del Agua",
  },
  {
    src: "/brands/cremigal.png",
    alt: "Cremigal",
  },
  {
    src: "/brands/emperador.png",
    alt: "Emperador",
  },
  {
    src: "/brands/los-alisos.png",
    alt: "Los alisos",
  },
  {
    src: "/brands/tonadita.png",
    alt: "Tonadita",
  },
];
