export const classicHamburguersDataWithBread = [
  {
    src: "/productsHome/burger.png",
    alt: "60 medallones de carne con pan",
    title: "60 medallones de carne con pan",
    brandsrc: "/brands/la-conquista-fondo.jpg",
    description: "LA CONQUISTA 30 % Soja x 69 Grs",
    price: "$5.500",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 medallones de carne con pan",
    title: "36 medallones de carne con pan",
    brandsrc: "/brands/la-conquista-fondo.jpg",
    description: "LA CONQUISTA 30 % Soja x 69 Grs",
    price: "$4.000",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas con pan",
    title: "60 hamburguesas con pan",
    brandsrc: "/brands/boogys.png",
    description: "BOOGYS 100 % Carne x 69 Grs",
    price: "$10.900",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas con pan",
    title: "36 hamburguesas con pan",
    brandsrc: "/brands/boogys.png",
    description: "BOOGYS 100 % Carne x 69 Grs",
    price: "$6.800",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas con pan",
    title: "60 hamburguesas con pan",
    brandsrc: "/brands/victoria-fondo.png",
    description: "VICTORIA 100 % Carne x 80 Grs",
    price: "$11.800",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas con pan",
    title: "36 hamburguesas con pan",
    brandsrc: "/brands/victoria-fondo.png",
    description: "VICTORIA 100 % Carne x 80 Grs",
    price: "$7.800",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "72 hamburguesas con pan",
    title: "72 hamburguesas con pan",
    brandsrc: "/brands/unionganadera.png",
    description: "UNIÓN GANADERA 100 % Carne x 55 Grs",
    price: "$11.800",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas con pan",
    title: "36 hamburguesas con pan",
    brandsrc: "/brands/unionganadera.png",
    description: "UNIÓN GANADERA 100 % Carne x 55 Grs",
    price: "$6.500",
    width: "100",
    height: "100",
  },
];

export const classicHamburguersDataNoBread = [
  {
    src: "/productsHome/burger.png",
    alt: "60 medallones de carne sin pan",
    title: "60 medallones de carne sin pan",
    brandsrc: "/brands/la-conquista-fondo.jpg",
    description: "LA CONQUISTA 30 % Soja x 69 Grs",
    price: "$3.300",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "30 medallones de carne sin pan",
    title: "30 medallones de carne sin pan",
    brandsrc: "/brands/la-conquista-fondo.jpg",
    description: "LA CONQUISTA 30 % Soja x 69 Grs",
    price: "$1.900",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas sin pan",
    title: "60 hamburguesas sin pan",
    brandsrc: "/brands/boogys.png",
    description: "BOOGYS 100 % Carne x 69 Grs",
    price: "$8.900",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "30 hamburguesas sin pan",
    title: "30 hamburguesas sin pan",
    brandsrc: "/brands/boogys.png",
    description: "BOOGYS 100 % Carne x 69 Grs",
    price: "$4.900",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas sin pan",
    title: "60 hamburguesas sin pan",
    brandsrc: "/brands/victoria-fondo.png",
    description: "VICTORIA 100 % Carne x 80 Grs",
    price: "$10.300",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "30 hamburguesas sin pan",
    title: "30 hamburguesas sin pan",
    brandsrc: "/brands/victoria-fondo.png",
    description: "VICTORIA 100 % Carne x 80 Grs",
    price: "$5.700",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "72 hamburguesas sin pan",
    title: "72 hamburguesas sin pan",
    brandsrc: "/brands/unionganadera.png",
    description: "UNIÓN GANADERA 100 % Carne x 55 Grs",
    price: "$10.300",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas sin pan",
    title: "36 hamburguesas sin pan",
    brandsrc: "/brands/unionganadera.png",
    description: "UNIÓN GANADERA 100 % Carne x 55 Grs",
    price: "$5.700",
    width: "100",
    height: "100",
  },
];

export const hamburgerBrands = [
  {
    src: "/brands/la-conquista-fondo.jpg",
    alt: "La conquista",
  },
  {
    src: "/brands/boogys.png",
    alt: "Boogys",
  },
  {
    src: "/brands/victoria-fondo.png",
    alt: "Victoria",
  },
  {
    src: "/brands/unionganadera.png",
    alt: "Union ganadera",
  },
];
