export const classicHamburguersDataWithBread = [
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas con pan",
    title: "60 hamburguesas con pan",
    brandsrc: "/brands/la-defensa.png",
    description: "LA CONQUISTA 30 % Soja x 69 Grs",
    price: "$4.900",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas con pan",
    title: "36 hamburguesas con pan",
    brandsrc: "/brands/la-defensa.png",
    description: "LA CONQUISTA 30 % Soja x 69 Grs",
    price: "$3.300",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas con pan",
    title: "60 hamburguesas con pan",
    brandsrc: "/brands/la-defensa.png",
    description: "BOOGYS 100 % Carne x 69 Grs",
    price: "$9.200",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas con pan",
    title: "36 hamburguesas con pan",
    brandsrc: "/brands/la-defensa.png",
    description: "BOOGYS 100 % Carne x 69 Grs",
    price: "$6.100",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas con pan",
    title: "60 hamburguesas con pan",
    brandsrc: "/brands/la-defensa.png",
    description: "VICTORIA 100 % Carne x 80 Grs",
    price: "$11.800",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas con pan",
    title: "36 hamburguesas con pan",
    brandsrc: "/brands/la-defensa.png",
    description: "VICTORIA 100 % Carne x 80 Grs",
    price: "$7.800",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "72 hamburguesas con pan",
    title: "72 hamburguesas con pan",
    brandsrc: "/brands/la-defensa.png",
    description: "UNIÓN GANADERA 100 % Carne x 55 Grs",
    price: "$11.800",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas con pan",
    title: "36 hamburguesas con pan",
    brandsrc: "/brands/la-defensa.png",
    description: "UNIÓN GANADERA 100 % Carne x 55 Grs",
    price: "$6.600",
    width: "100",
    height: "100",
  },
];

export const classicHamburguersDataNoBread = [
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas sin pan",
    title: "60 hamburguesas sin pan",
    brandsrc: "/brands/la-defensa.png",
    description: "LA CONQUISTA 30 % Soja x 69 Grs",
    price: "$3.050",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas sin pan",
    title: "36 hamburguesas sin pan",
    brandsrc: "/brands/la-defensa.png",
    description: "LA CONQUISTA 30 % Soja x 69 Grs",
    price: "$1.700",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas sin pan",
    title: "60 hamburguesas sin pan",
    brandsrc: "/brands/la-defensa.png",
    description: "BOOGYS 100 % Carne x 69 Grs",
    price: "$7.900",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas sin pan",
    title: "36 hamburguesas sin pan",
    brandsrc: "/brands/la-defensa.png",
    description: "BOOGYS 100 % Carne x 69 Grs",
    price: "$4.300",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "60 hamburguesas sin pan",
    title: "60 hamburguesas sin pan",
    brandsrc: "/brands/la-defensa.png",
    description: "VICTORIA 100 % Carne x 80 Grs",
    price: "$10.250",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas sin pan",
    title: "36 hamburguesas sin pan",
    brandsrc: "/brands/la-defensa.png",
    description: "VICTORIA 100 % Carne x 80 Grs",
    price: "$5.670",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "72 hamburguesas sin pan",
    title: "72 hamburguesas sin pan",
    brandsrc: "/brands/la-defensa.png",
    description: "UNIÓN GANADERA 100 % Carne x 55 Grs",
    price: "$10.250",
    width: "100",
    height: "100",
  },
  {
    src: "/productsHome/burger.png",
    alt: "36 hamburguesas sin pan",
    title: "36 hamburguesas sin pan",
    brandsrc: "/brands/la-defensa.png",
    description: "UNIÓN GANADERA 100 % Carne x 55 Grs",
    price: "$5.670",
    width: "100",
    height: "100",
  },
];

export const hamburgerBrands = [
  {
    src: "/brands/la-conquista-fondo.jpg",
    alt: "La conquista",
  },
  {
    src: "/brands/victoria-fondo.png",
    alt: "Victoria",
  },
  {
    src: "/brands/boogys.png",
    alt: "Boogys",
  },
  {
    src: "/brands/unionganadera.png",
    alt: "Union ganadera",
  },
];
