export const potatoes = [
  {
    src: "/products/papas/coolmind.png",
    alt: "Bastón Caja",
    title: "Bastón Caja",
    description: "COOL MIND Caja x 15 Kg",
    price: "$8.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/coolmind.png",
    alt: "Bastón Unidad",
    title: "Bastón Unidad",
    description: "COOL MIND x 2500 Grs",
    price: "$1.490",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/smiles.png",
    alt: "Smiles Caja",
    title: "Smiles Caja",
    description: "MC CAIN Caja x 9 Kg",
    price: "$8.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/smiles.png",
    alt: "Smiles Unidad",
    title: "Smiles Unidad",
    description: "MC CAIN x 1500 Grs",
    price: "$1.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/noissete-mc-cain.png",
    alt: "Noissetes Caja",
    title: "Noissetes Caja",
    description: "MC CAIN Caja x 10 Kg",
    price: "$9.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/noissete-mc-cain.png",
    alt: "Noissetes Unidad",
    title: "Noissetes Unidad",
    description: "MC CAIN x 2500 Grs",
    price: "$2.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/aros-cebolla.png",
    alt: "Aros de cebolla Caja",
    title: "Aros de cebolla Caja",
    description: "MC CAIN Caja x 10 Kg",
    price: "$20.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/aros-cebolla.png",
    alt: "Aros de cebolla Unidad",
    title: "Aros de cebolla Unidad",
    description: "MC CAIN x 1000 Grs",
    price: "$2.160",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/chips.png",
    alt: "Chips Caja",
    title: "Chips Caja",
    description: "SIMPLOT Caja x 14 Kg",
    price: "$10.490",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/chips.png",
    alt: "Chips Unidad",
    title: "Chips Unidad",
    description: "SIMPLOT x 2000 Grs",
    price: "$1.590",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/simplot-rusticas.png",
    alt: "Rústicas Caja",
    title: "Rústicas Caja",
    description: "SIMPLOT Caja x 10 Kg",
    price: "$7.990",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/simplot-rusticas.png",
    alt: "Rústicas Unidad",
    title: "Rústicas Unidad",
    description: "SIMPLOT x 2000 Grs",
    price: "$1.690",
    width: "100",
    height: "100",
  },
];

export const potatoesBrands = [
  {
    src: "/brands/simplot.png",
    alt: "La defensa",
  },
  {
    src: "/brands/mccain.png",
    alt: "Victoria",
  },
];
