export const potatoes = [
  {
    src: "/products/papas/coolmind.png",
    alt: "Cool Mind Caja",
    title: "Cool Mind Caja",
    description: "Bastón caja 15 Kg SMILES caja x 9 Kg 2500 Grs",
    price: "$8.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/coolmind.png",
    alt: "Cool Mind Unidad",
    title: "Cool Mind Unidad",
    description: "2500 Grs",
    price: "$1.490",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/smiles.png",
    alt: "Mc Cain Caja",
    title: "Mc Cain Caja",
    description: "Smiles caja x 9 Kg 1500 Grs",
    price: "$8.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/smiles.png",
    alt: "Mc Cain Unidad",
    title: "Mc Cain Unidad",
    description: "1500 Grs",
    price: "$1.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/noissete-mc-cain.png",
    alt: "Mc Cain Caja",
    title: "Mc Cain Caja",
    description: "Noissetes Caja x 10 Kg 2500 Grs",
    price: "$9.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/noissete-mc-cain.png",
    alt: "Mc Cain Unidad",
    title: "Mc Cain Unidad",
    description: "2500 Grs",
    price: "$2.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/aros-cebolla.png",
    alt: "Mc Cain Caja aros de cebolla",
    title: "Mc Cain Caja aros de cebolla COMPLETAR",
    description: "Aros de cebolla caja x 10 Kg 1000 Grs",
    price: "$20.500",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/aros-cebolla.png",
    alt: "Mc Cain Unidad aros de cebolla",
    title: "Mc Cain Unidad aros de cebolla COMPLETAR",
    description: "1000 Grs",
    price: "$2.160",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/chips.png",
    alt: "Simplot Caja",
    title: "Simplot Caja",
    description: "Chips caja x 14 Kg 2000 Grs",
    price: "$10.490",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/chips.png",
    alt: "Simplot Unidad",
    title: "Simplot Unidad",
    description: "2000 Grs",
    price: "$1.590",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/simplot-rusticas.png",
    alt: "Simplot Caja",
    title: "Simplot Caja",
    description: "Rusticas caja x 10 Kg 2000 Grs",
    price: "$7.990",
    width: "100",
    height: "100",
  },
  {
    src: "/products/papas/simplot-rusticas.png",
    alt: "Simplot Unidad",
    title: "Simplot Unidad",
    description: "2000 Grs",
    price: "$1.690",
    width: "100",
    height: "100",
  },
];

export const potatoesBrands = [
  {
    src: "/brands/simplot.png",
    alt: "La defensa",
  },
  {
    src: "/brands/mccain.png",
    alt: "Victoria",
  },
];
