import Head from "next/head";
import { Roboto } from "next/font/google";

//Componentes
import Banner from "@/components/Banner";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SocialMedia from "@/components/SocialMedia";
import Shipping from "@/components/Shipping";
import ProductsHomeSection from "@/components/ProductsHomeSection";
import Phrase from "@/components/Phrase";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Pack Eventos / Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={roboto.className}>
        <div>
          <NavBar />
          <Banner />
          <SocialMedia />
          <Shipping />
          <ProductsHomeSection />
          <Phrase />

          <Footer />
        </div>
      </main>
    </>
  );
}
